import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense } from "react";

import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import "@styles/global.css";

// Resource definitions for Refine
const resources = [
  {
    name: "profiles",
    list: "/profiles",
    create: "/profiles/create",
    edit: "/profiles/edit/:id",
    show: "/profiles/show/:id",
    meta: {
      label: "Profiles",
      icon: "user",
    },
  },
  {
    name: "badges",
    list: "/badges",
    create: "/badges/create",
    edit: "/badges/edit/:id",
    meta: {
      label: "Badges",
      icon: "badge",
    },
  },
  {
    name: "experiences",
    list: "/experiences",
    create: "/experiences/create",
    edit: "/experiences/edit/:id",
    meta: {
      label: "Experiences",
      icon: "briefcase",
    },
  },
  {
    name: "profile_links",
    meta: {
      label: "Profile Links",
      hide: true,
    },
  },
  {
    name: "profile_badges",
    meta: {
      label: "Profile Badges",
      hide: true,
    },
  },
  {
    name: "experience_badges",
    meta: {
      label: "Experience Badges",
      hide: true,
    },
  },
];

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <GitHubBanner />
          <RefineKbarProvider>
            <DevtoolsProvider>
              <Refine
                routerProvider={routerProvider}
                dataProvider={dataProvider}
                authProvider={authProviderClient}
                resources={resources}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  useNewQueryKeys: true,
                  projectId: "W1RHVO-GgDLZM-dCCcJJ",
                }}
              >
                {children}
                <RefineKbar />
              </Refine>
            </DevtoolsProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
